pip install torch
pip install librosa
pip install matplotlib
pip install pandas
pip install torchaudio
pip install pretty_midi
pip install einops
pip install torchlibrosa
pip install tqdm
pip install museval
pip install mir_eval
pip install ipython